services:
  - type: web
    name: telegram-movie-link-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: WEBHOOK_URL
        value: https://your-service-name.onrender.com
